services:
  - type: web
    name: lead-to-lease-chat
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4
      - key: OPENAI_TIMEOUT
        value: "60.0"
      - key: OPENAI_MAX_RETRIES
        value: "3"
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: PROPERTY_ADDRESS
        value: "123 Luxury Lane, Downtown District, NY 10001"
      - key: PROPERTY_NAME
        value: "Luxury Apartments at Main Street"
      - key: LEASING_OFFICE_PHONE
        value: "(555) 123-4567"
      - key: FRONTEND_URL
        value: "https://micro-service-frontend.onrender.com"
